In [13]:
import os
import pandas as pd

from project_huishoudboekje.config import GeneralSettings as GenSet

from project_huishoudboekje.read_asn import ReadAsn

In [11]:
list_files = next(os.walk(GenSet.project_path / f'data/ASN Bank'), (None, None, []))[2]

In [18]:
list_out = []

for file in list_files:
    df = pd.read_csv(GenSet.project_path / f'data/ASN Bank/{file}', header=None)

    list_out.append(df)

df = pd.concat(list_out, ignore_index=True)

In [19]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,01-02-2026,NL61ASNB0267337108,NL12ASNB8850618603,SCHUITEMAKER J S,NaN,NaN,NaN,EUR,6128.67,EUR,-25.00,01-02-2026,01-02-2026,3700,POV,783895,NaN,'Spaarpot Julian',3,'Sparen'
1,02-02-2026,NL61ASNB0267337108,NL98INGB0002712510,OHRA Schadeverzekeringen,NaN,NaN,NaN,EUR,6103.67,EUR,-138.91,02-02-2026,02-02-2026,9714,EIC,1194192,NaN,'Europese incasso: NL-Relatie 8152833 / Versch...,3,'Verzekeringen'
2,02-02-2026,NL61ASNB0267337108,NL42DEUT0265288134,Marktplaats via Online Payments Stichting,NaN,NaN,NaN,EUR,5964.76,EUR,-35.40,02-02-2026,02-02-2026,9806,IDE,4276307,NaN,'tradeb0ada6e372 8152264176898474 m2359143413:...,3,'Overig'
3,03-02-2026,NL61ASNB0267337108,DK8789000000014387,Stripe Technology Europe Ltd,NaN,NaN,NaN,EUR,5929.36,EUR,5.85,03-02-2026,03-02-2026,8809,OVS,910482,NaN,'DK8789000000014387-Stripe Technology Europe L...,3,'Overig'
4,03-02-2026,NL61ASNB0267337108,NL12COBA0733959555,ODIDO NETHERLANDS B.V.,NaN,NaN,NaN,EUR,5935.21,EUR,-15.48,03-02-2026,03-02-2026,9714,EIC,1041514,NaN,'Europese incasso: NL-Mob 0625322714 Klantnr 1...,3,'Internet TV & Bellen'

In [23]:
df['PARTY'] = df.iloc[:, 3].fillna('').astype(str) + ' - ' + df.iloc[:, 17].str[1:-1].str.split().str[:3].str.join(sep=" ")

In [31]:
df['PARTY'] = df['PARTY'].str.strip(' - ')

In [32]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,PARTY
109,27-02-2026,NL61ASNB0267337108,NaN,NaN,NaN,NaN,NaN,EUR,102390.15,EUR,...,27-02-2026,27-02-2026,7906,BEA,4831402,NaN,'Albert Heijn 1628 >AMERSFOOR27.02.2026 16...,5,'Boodschappen',Albert Heijn 1628
110,28-02-2026,NL61ASNB0267337108,NaN,NaN,NaN,NaN,NaN,EUR,102387.76,EUR,...,28-02-2026,28-02-2026,7906,BEA,1079497,NaN,'Jumbo Amersfoort PSE >AMERSFOOR28.02.2026 10...,5,'Boodschappen',Jumbo Amersfoort PSE
111,28-02-2026,NL61ASNB0267337108,NaN,NaN,NaN,NaN,NaN,EUR,102298.14,EUR,...,28-02-2026,28-02-2026,7906,BEA,2474925,NaN,'Karwei Amersfoort >AMERSFOOR28.02.2026 16...,5,'Klussen & onderhoud',Karwei Amersfoort >AMERSFOOR28.02.2026
112,28-02-2026,NL61ASNB0267337108,NL70ASNB8825114125,ASN Sparen,NaN,NaN,NaN,EUR,102133.81,EUR,...,28-02-2026,28-02-2026,3724,NGI,3000071,NaN,'Referentie: 23f4a75a-b4e9-4e23-b7f8-8977e85e88',5,'Sparen',ASN Sparen - Referentie: 23f4a75a-b4e9-4e23-b7...
113,28-02-2026,NL61ASNB0267337108,NL04ADYB2017400157,KARWEI,NaN,NaN,NaN,EUR,7133.81,EUR,...,28-02-2026,28-02-2026,9806,IDE,3001441,NaN,'X3CLXLM5D9BQ75Q92KTJ0 7180294455310951 620002...,5,'Overig',KARWEI - X3CLXLM5D9BQ75Q92KTJ0 718029445531095...

In [30]:
df['PARTY'] = df.apply(lambda x: x.iloc[17][1:-1].str.split()[:3].join(sep=" ") if x.iloc[3] is None else x.iloc[3] + ' - ' + x.iloc[17][1:-1].split()[:3].join(sep=" "), axis=1)

AttributeError: 'list' object has no attribute 'join'

In [25]:
df.loc[df.PARTY.isnull(), :]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, PARTY]
Index: []

[0 rows x 21 columns]